# Generated by Django 5.2.4 on 2025-07-31 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('system', models.CharField(choices=[('skeleton', 'Squelette'), ('organs', 'Organes'), ('muscles', 'Muscles'), ('nervous', 'Système nerveux'), ('blood', 'Système sanguin')], max_length=20)),
                ('model_file', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('body_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='anatomy.bodypart')),
            ],
        ),
    ]
